#!/bin/bash

# Copyright 2016  - Emanuele Paiano (emanuelepaiano.github.io)
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated 
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of 
# the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
# THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Secure Hash Password generator 
#
# Type -c arguments for password confirm (useful to generate password)
#
# loop encrypt iterations... 
# high value=secure 
# low values=weak
# tryLoop=0 --> standard SHA password

tryLoop=50
param='-a 256'


echo "Secure Hash password generator"

echo ""

echo -n "Password:"

read -s password

if [ "$1" == "-c" ]
then
      echo ""
      echo -n "Retype password:"
      read -s pwdctrl  
      if [ "$pwdctrl" != "$password" ]
      then
                echo ""
                echo "Passwords not match!"
                exit
      fi
      
fi

echo ""

echo -n "Generating Hash..."

x=1

while [ $x -le $[$tryLoop-1] ]

do
        
        password=$(echo $password |tr '\n' ' ')

        tmp=$password

        password=$(echo -n $password | shasum $param | cut -f1 -d " ")

        password=$tmp$password
        
        x=$[$x+1]
        
done

echo ""

password=$(echo -n $password | shasum $param | cut -f1 -d " ")

echo ""

echo -n "Hash password is: "

echo $password
